<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_1d</name>
   <tag></tag>
   <elementGuidId>e4a0567d-c209-4bff-ac04-14fa4f06b77c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;1dayTab&quot;)/span[@class=&quot;VfPpkd-YVzG2b&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='1dayTab']/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.VfPpkd-YVzG2b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;1D&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1dayTab&quot;)/span[@class=&quot;VfPpkd-YVzG2b&quot;]</value>
      <webElementGuid>73962725-16cc-47e9-9ea1-8279151a3b23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='1dayTab']/span[2]</value>
      <webElementGuid>d97312b9-4f1a-4e8c-b975-2ca7195fa5a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/button/span[2]</value>
      <webElementGuid>98126ab4-bb21-412e-b673-00760aaaa425</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
