<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_searchfield</name>
   <tag></tag>
   <elementGuidId>bb92c7ed-f576-42df-859c-f0d3896e188f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.L6J0Pc.ZB3Ebc.nz7KN > div.d1dlne > input.Ax4B8.ZAGvjd</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=combobox[name=&quot;Search for stocks, ETFs &amp; more&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a92cfef5-36d6-4df9-a2e5-41f725af3b4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Ax4B8 ZAGvjd</value>
      <webElementGuid>793910f3-726b-462c-9658-074af8f7d59a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>67a5c21e-216d-4a8d-8097-d29ba55032d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f87c4bf2-6d3d-4162-896a-6f1397d4705e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search for stocks, ETFs &amp; more</value>
      <webElementGuid>696fd66f-794d-4625-810b-b79f8dff6d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>c3b39d5e-4fab-4201-bd0c-5204d6ab4ec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1c929018-2e37-4eda-b892-7d3482a8bf2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5e864729-fec2-4dd3-b8a8-3f24c488b4c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>5f6bd556-0b51-4303-85c1-f261955bdd05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>dSO9oc</value>
      <webElementGuid>e5c28705-3db6-4135-ac30-e21fd8738757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsaction</name>
      <type>Main</type>
      <value>input:YPqjbf; keydown:I481le; click:cOuCgd</value>
      <webElementGuid>506178b6-2a84-443d-838e-ae18e2477293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>nngdp5</value>
      <webElementGuid>302bbd25-00b5-4254-aafd-64c974c1b11e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yDmH0d&quot;)/c-wiz[@class=&quot;zQTmif SSPGKf ccEnac&quot;]/div[@class=&quot;T4LgNb&quot;]/div[@class=&quot;KdK6Xc&quot;]/div[@class=&quot;e1AOyf&quot;]/div[@class=&quot;AyKEed&quot;]/div[@class=&quot;M52nVb ytPNkd E6c19c&quot;]/div[@class=&quot;L6J0Pc ZB3Ebc nz7KN&quot;]/div[@class=&quot;d1dlne&quot;]/input[@class=&quot;Ax4B8 ZAGvjd&quot;]</value>
      <webElementGuid>ea6d78c5-eaa1-4e91-8eea-da95b1f2db6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[2]</value>
      <webElementGuid>a887805f-d389-4ffe-9f7d-049626ac1a2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='yDmH0d']/c-wiz[2]/div/div[3]/div[3]/div/div/div/div/input[2]</value>
      <webElementGuid>bf915507-07d9-4d11-9bfa-6bc478492981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/input[2]</value>
      <webElementGuid>5cb9ba84-1cfc-42db-8f45-b821ae6f8e36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>e9be31df-8250-4984-ab5c-64ee15ff4a75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
